python train.py --algo ppo  --seed 123 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 666 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 987 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 285 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 517 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 456 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 222 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 234 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 861 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
python train.py --algo ppo  --seed 369 --env CartPole-v1 --tensorboard-log $PWD/tensorboard --hyperparams device:$1
