python train.py --algo nhpo --classifier $2 --aece CE --seed 123 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 666 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 987 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 285 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 517 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 456 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 222 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 234 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 861 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
python train.py --algo nhpo --classifier $2 --aece CE --seed 369 --env CartPole-v1 --tensorboard-log $PWD/tensorboard-$2 --hyperparams device:$1
